services:
  db:
    image: mariadb:10.11.8
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: your_mariadb_root_password
      MARIADB_DATABASE: your_mariadb_database_name
      MARIADB_USER: your_mariadb_username
      MARIADB_PASSWORD: your_mariadb_password
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_mariadb_username
      WORDPRESS_DB_PASSWORD: your_mariadb_password
      WORDPRESS_DB_NAME: your_mariadb_database_name
volumes:
  mariadb_data: {}
